### ISSUE TITLE
fails with "Unknown arch: sm61"

### ISSUE THREAD

**Issue by screig** [quantalea/AleaGPUTutorial#11]
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Alea;

namespace cuda_lib_002
{
    public class cuda_lib_002
    {
        public static void somefunc()
        {
            var worker = Gpu.Default;
            var devices = Device.Devices;
            var numGpus = devices.Length;
            foreach (var device in devices)
            {
                // print device information to standard output
                device.Print();
                var id = device.Id;
                var arch = device.Arch;
                var numMultiProc = device.Attributes.MultiprocessorCount;
            }
        }
    }
}
```

This crashes, with the following message:

Message = "Unknown arch: sm61"
at A.cf5aded17df9f7cc4c132234dda010fa7.clo@331-596.Invoke(String message)
at A.cf5aded17df9f7cc4c132234dda010fa7.-ctor@351-230.Invoke(Unit unitVar)
at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
at System.Lazy`1.get_Value()
at Alea.Device.get_Cores()

package file

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Alea" version="3.0.0-beta17" targetFramework="net452" />
  <package id="Alea.Fody" version="3.0.0-beta17" targetFramework="net452" developmentDependency="true" />
  <package id="Alea.Parallel" version="3.0.0-beta17" targetFramework="net452" />
  <package id="Fody" version="1.30.0-beta01" targetFramework="net452" developmentDependency="true" />
</packages>
```

device:
[0] = {GeForce GTX 1060 6GB}

Cuda 8.0.44

**Comment by degloff** [comment]
This should now work with Alea GPU V3 released.
